"""Add new column 'time' to the reminders table

Revision ID: a1c918cae79f
Revises: 6004c9e7ab3e
Create Date: 2025-11-17 13:41:15.831212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c918cae79f'
down_revision: Union[str, Sequence[str], None] = '6004c9e7ab3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'time')
    # ### end Alembic commands ###
